export type Deal = {
  id: number;
  stage: string;
  company: string | null;
  contact_first_name: string | null;
  contact_last_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  day_of_contact_name: string | null;
  day_of_contact_phone: string | null;
  event_date: string | null;
  event_start_time: string | null;
  event_end_time: string | null;
  event_type: string | null;
  venue_name: string | null;
  venue_address: string | null;
  guest_count: number | null;
  package_name: string | null;
  flavors: string | null;
  toppings: string | null;
  extras: string | null;
  staff_count: number | null;
  labor_hours: number | null;
  total_with_tax: number | null;
  subtotal_pretax: number | null;
  amount_paid: number | null;
  signed_contract_total: number | null;
  deposit_amount: number | null;
  payment_status: string;
  boomerang_reason: string | null;
  last_outbound_at: string | null;
  is_active: number;
  archived: number;
  tax_exempt: number;
  notes: string | null;
  lead_source: string | null;
  how_did_you_hear: string | null;
  created_at: string;
  updated_at: string;
};
